import type { Movie, StaticMeta, ColorScheme } from '../types.js';

export const FACTS: Record<string, string> = {
  "The Lion King": "Most of Disney's top animators chose Pocahontas over this project, expecting it to be the bigger hit — Lion King ended up grossing more than three times as much",
  "Toy Story": "The first feature-length CGI film ever made — Pixar's computers ran 24 hours a day for over a year just to render it",
  "Finding Nemo": "The entire crew took scuba diving lessons, and the story team spent weeks at the Great Barrier Reef before drawing a single frame",
  "Beauty and the Beast": "The first animated film ever nominated for Best Picture at the Academy Awards",
  "The Little Mermaid": "Howard Ashman and Alan Menken structured the songs as a complete Broadway musical — their approach kicked off the entire Disney Renaissance",
  "Up": "The opening montage has zero dialogue, just music and visuals, and has since become a staple of film school curricula worldwide",
  "Aladdin": "Robin Williams improvised so extensively that production recorded over 16 hours of material — far more than they could write around",
  "Inside Out": "Pixar consulted with neuroscientists and psychiatrists throughout development. Several mental health professionals cried at early screenings.",
  "Coco": "Became the highest-grossing film of all time in Mexico upon release",
  "Frozen": "Let It Go was written in one session — the Lopezes say it flowed out in a single sitting and barely changed before the final cut",
  "The Incredibles": "Brad Bird pitched it as 'a James Bond film where the spy is a middle-aged dad' — Pixar greenlit it on that description alone",
  "WALL·E": "One of the most dialogue-sparse major studio films ever made — long stretches pass with no spoken words at all",
  "Mulan": "The first Disney protagonist to win her final battle through a clever trick rather than magic, brute strength, or being rescued",
  "Tangled": "Rapunzel's hair required Pixar to build an entirely new simulation system — 100,000+ individual strands, each animated separately",
  "Monsters, Inc.": "Boo's real name is briefly visible on her bedroom door in the final scene — it's Mary",
  "Moana": "Auli'i Cravalho was discovered at a charity event just days before the casting deadline closed. She had never auditioned for anything before.",
  "Ratatouille": "Brad Bird took over mid-production from a story that wasn't working. The finished film shares almost nothing with the original concept.",
  "Toy Story 3": "The villain Lotso was conceived before the original Toy Story, but cut — the technology to animate plush fur didn't exist yet",
  "Lilo & Stitch": "Originally pitched as a story about a little girl and her dog, set in Kansas. The alien was added specifically to avoid making another fairy tale.",
  "The Emperor's New Groove": "Was originally a serious Inca-set musical called Kingdom of the Sun. Almost the entire production was scrapped and rebuilt from scratch.",
  "Cinderella": "Walt Disney used the film's profits to pay off wartime studio debt and fund early development of what would become Disneyland",
  "Sleeping Beauty": "Every frame was painted in widescreen format specifically for the new Cinemascope theater technology — the production took six years",
  "Encanto": "Lin-Manuel Miranda wrote all eight original songs while simultaneously running Hamilton on Broadway",
  "Soul": "Jon Batiste performed the jazz sequences live so the animators could build Joe Gardner's playing style around his actual movements",
  "Zootopia": "The city required a different animation rig for every species — the fur simulation alone involves over 800,000 individual strands on the main characters",
  "Raya and the Last Dragon": "Before designing a single character, the production team traveled to Thailand, Laos, Cambodia, Vietnam, Indonesia, and the Philippines",
  "Turning Red": "The first Pixar feature set in Canada, and the first Pixar feature film directed solely by a woman of color",
  "Elemental": "Ember's fire effects required Pixar to build a new simulation system — water, fire, and air characters each needed their own physics engine",
  "Hercules": "The five Muses were written as a modern take on the ancient Greek chorus — deliberately anachronistic, which is exactly why the directors loved the idea",
  "Bambi": "Disney kept live deer on the studio lot for animators to study. The film took five years to produce and remains one of the few Disney features with no human villain",
  "Wreck-It Ralph": "Required licensing deals with Capcom, Namco, Sega, and others to include real video game characters. The 'Game Central Station' power strip interior was the team's favorite concept to design",
  "Tarzan": "Phil Collins recorded the entire soundtrack in multiple languages himself for international releases — not just the English version",
  "The Jungle Book": "The last film Walt Disney personally supervised — he died in December 1966, eight months before its October 1967 release. He never saw the finished cut",
  "Brave": "The first Pixar film with a female protagonist, and the first set in a real historical period and culture rather than a fantasy world",
  "Toy Story 2": "A production assistant accidentally deleted 90% of the finished film by running a system cleanup script. It was only restored from a backup on the technical director's home computer",
  "Toy Story 4": "Bo Peep was deliberately written out of Toy Story 3 so she could return here. Woody is separated from the ensemble for most of the runtime — a first for the series",
  "Lady and the Tramp": "The first Disney animated film in CinemaScope widescreen, and the first set in a contemporary American neighborhood rather than a fairy tale world",
  "101 Dalmatians": "The first Disney film to use xerography — photocopying animation drawings instead of hand-inking — which made animating 101 spotted dogs without losing the animators actually possible",
  "Peter Pan": "Hans Conried voiced both Captain Hook and Mr. Darling — a deliberate echo of the stage tradition where one actor plays both roles",
  "The Hunchback of Notre Dame": "Frollo's 'Hellfire' is one of the most adult songs in Disney history — about lust, sin, and burning a city. Internal research showed it was the most emotionally intense Disney film to date",
  "Snow White": "The industry called it 'Disney's Folly' before release and assumed it would fail. Disney mortgaged his house to fund production when it ran over budget",
  "Big Hero 6": "Based on a little-known Marvel Comics property — the only Disney animated feature built on Marvel IP. San Fransokyo required an entirely new rendering technique to generate a city of that scale",
  "Cars": "John Lasseter wrote the story after a cross-country road trip with his family — he took it specifically to reconnect with them after years of overworking",
  "Pinocchio": "Many animators consider it the technical peak of Disney's golden age — the special effects animation for fire, water, and smoke used techniques that weren't surpassed for decades",
  "Fantasia": "Premiered with 'Fantasound,' a custom multi-speaker audio system that predated modern surround sound by decades — most theaters couldn't install it, limiting its initial run",
  "Luca": "Director Enrico Casarosa based it on his own childhood summers along the Italian Riviera and a friendship with a boy from a very different background",
  "Pocahontas": "Disney's first film based on a real historical person. The production consulted with the Pamunkey Nation, though the film still drew criticism for taking significant liberties with history",
  "Alice in Wonderland": "Disney had been developing Alice since the late 1930s — nearly fifteen years passed between early story work and the 1951 release",
  "Inside Out 2": "Broke Pixar's opening weekend record and became the highest-grossing animated film of 2024, the first film to cross $1 billion globally in several years",
  "The Princess and the Frog": "Disney's first Black princess, and the studio's deliberate return to hand-drawn 2D animation after years of CGI-only features",
  "A Bug's Life": "DreamWorks rushed Antz into theaters two months earlier to win the 'bug movie' race — both projects were in development simultaneously, and Katzenberg had learned about A Bug's Life through his time at Pixar",
  "Dumbo": "At 64 minutes, one of Disney's shortest features — made quickly and cheaply specifically to recover losses from Fantasia and Bambi's underperformance",
  "Robin Hood": "Reused animation from multiple earlier films — Maid Marian's dance movements are traced from Snow White, and crowd scenes recycle Jungle Book footage",
  "Monsters University": "Pixar's first prequel. The team designed over 120 distinct monster species for the university setting, each requiring its own simulation rig for fur, slime, or appendages",
  "Treasure Planet": "One of Disney's biggest box office failures, losing an estimated $70 million — it directly contributed to the closure of Disney's Florida animation studio",
  "Atlantis: The Lost Empire": "Linguist Marc Okrand — creator of the Klingon language for Star Trek — was hired to build a complete Atlantean language with real grammar and vocabulary",
  "The Great Mouse Detective": "Often credited as the film that saved Disney Animation — its success under extreme budget constraints convinced the studio to greenlight The Little Mermaid",
  "The Rescuers Down Under": "The first Disney animated sequel, and the first Disney feature to use the CAPS digital paint pipeline throughout — no hand-painted cels at all",
  "The Sword in the Stone": "Based on T.H. White's Arthurian novel, one of Disney's personal favorites. Among the last films to closely reflect his own creative direction before his death in 1966",
  "The Aristocats": "The first film greenlighted after Walt Disney's death — he had approved the concept just days before he died in December 1966",
  "Bolt": "John Lasseter's first film to oversee as head of Disney Animation after Pixar's acquisition by Disney. He had the story restructured to make Bolt's delusion more sympathetic",
  "Meet the Robinsons": "The film's motto 'Keep Moving Forward' was taken from a real Walt Disney quote. Lasseter reportedly showed the team the quote when he took over and said it applied to them too",
  "Brother Bear": "Phil Collins returned to score the film — his second Disney soundtrack after Tarzan. It was the last production from Disney's Florida studio before it closed in 2004",
  "The Rescuers": "Based on a series of children's books by Margery Sharp. The first Disney animated film successful enough to spawn a direct sequel",
  "Oliver & Company": "Set in contemporary New York City with Billy Joel, Bette Midler, and Cheech Marin in the voice cast — the first Disney animated film to receive a wide opening-weekend theatrical release",
  "Onward": "Director Dan Scanlon wrote it to process losing his father when he was very young — he and his brother had only a single voicemail recording of their father's voice, and the film grew from that",
  "Chicken Little": "Disney's first fully CGI animated feature, produced independently after the Pixar partnership temporarily dissolved",
  "Incredibles 2": "Picked up exactly where the first film ended — fourteen years later in real life, five minutes later in the story. Earned $182 million opening weekend, shattering Pixar's record",
  "Ralph Breaks the Internet": "The Disney Princess scene alone required years of legal clearances — Disney had to negotiate rights for every princess separately, including properties from their own studio",
  "The Good Dinosaur": "Pixar's most troubled production — the original director, story, and nearly all characters were replaced mid-production. It released the same year as Inside Out, making 2015 Pixar's strangest year",
};

export const MAIN: Movie[] = [
  { seed:1, name:"The Lion King", year:1994, studio:"Disney", imdb:"https://www.imdb.com/title/tt0110357/" },
  { seed:2, name:"Toy Story", year:1995, studio:"Pixar", imdb:"https://www.imdb.com/title/tt0114709/" },
  { seed:3, name:"Finding Nemo", year:2003, studio:"Pixar", imdb:"https://www.imdb.com/title/tt0266543/" },
  { seed:4, name:"Beauty and the Beast", year:1991, studio:"Disney", imdb:"https://www.imdb.com/title/tt0101414/" },
  { seed:5, name:"The Little Mermaid", year:1989, studio:"Disney", imdb:"https://www.imdb.com/title/tt0097757/" },
  { seed:6, name:"Up", year:2009, studio:"Pixar", imdb:"https://www.imdb.com/title/tt1049413/" },
  { seed:7, name:"Aladdin", year:1992, studio:"Disney", imdb:"https://www.imdb.com/title/tt0103639/" },
  { seed:8, name:"Inside Out", year:2015, studio:"Pixar", imdb:"https://www.imdb.com/title/tt2096673/" },
  { seed:9, name:"Coco", year:2017, studio:"Pixar", imdb:"https://www.imdb.com/title/tt2380307/" },
  { seed:10, name:"Frozen", year:2013, studio:"Disney", imdb:"https://www.imdb.com/title/tt2294629/" },
  { seed:11, name:"The Incredibles", year:2004, studio:"Pixar", imdb:"https://www.imdb.com/title/tt0317705/" },
  { seed:12, name:"WALL·E", year:2008, studio:"Pixar", imdb:"https://www.imdb.com/title/tt0910970/" },
  { seed:13, name:"Mulan", year:1998, studio:"Disney", imdb:"https://www.imdb.com/title/tt0120762/" },
  { seed:14, name:"Tangled", year:2010, studio:"Disney", imdb:"https://www.imdb.com/title/tt0398286/" },
  { seed:15, name:"Monsters, Inc.", year:2001, studio:"Pixar", imdb:"https://www.imdb.com/title/tt0198781/" },
  { seed:16, name:"Moana", year:2016, studio:"Disney", imdb:"https://www.imdb.com/title/tt3521164/" },
  { seed:17, name:"Ratatouille", year:2007, studio:"Pixar", imdb:"https://www.imdb.com/title/tt0382932/" },
  { seed:18, name:"Toy Story 3", year:2010, studio:"Pixar", imdb:"https://www.imdb.com/title/tt0435761/" },
  { seed:19, name:"Lilo & Stitch", year:2002, studio:"Disney", imdb:"https://www.imdb.com/title/tt0275847/" },
  { seed:20, name:"The Emperor's New Groove", year:2000, studio:"Disney", imdb:"https://www.imdb.com/title/tt0120917/" },
  { seed:21, name:"Cinderella", year:1950, studio:"Disney", imdb:"https://www.imdb.com/title/tt0042332/" },
  { seed:22, name:"Hercules", year:1997, studio:"Disney", imdb:"https://www.imdb.com/title/tt0119282/" },
  { seed:23, name:"Sleeping Beauty", year:1959, studio:"Disney", imdb:"https://www.imdb.com/title/tt0053285/" },
  { seed:24, name:"Encanto", year:2021, studio:"Disney", imdb:"https://www.imdb.com/title/tt2953050/" },
  { seed:25, name:"Soul", year:2020, studio:"Pixar", imdb:"https://www.imdb.com/title/tt2948372/" },
  { seed:26, name:"Zootopia", year:2016, studio:"Disney", imdb:"https://www.imdb.com/title/tt2948356/" },
  { seed:27, name:"Bambi", year:1942, studio:"Disney", imdb:"https://www.imdb.com/title/tt0034492/" },
  { seed:28, name:"Wreck-It Ralph", year:2012, studio:"Disney", imdb:"https://www.imdb.com/title/tt1772341/" },
  { seed:29, name:"Tarzan", year:1999, studio:"Disney", imdb:"https://www.imdb.com/title/tt0120855/" },
  { seed:30, name:"The Jungle Book", year:1967, studio:"Disney", imdb:"https://www.imdb.com/title/tt0061852/" },
  { seed:31, name:"Brave", year:2012, studio:"Pixar", imdb:"https://www.imdb.com/title/tt1217209/" },
  { seed:32, name:"Toy Story 2", year:1999, studio:"Pixar", imdb:"https://www.imdb.com/title/tt0120363/" },
  { seed:33, name:"Toy Story 4", year:2019, studio:"Pixar", imdb:"https://www.imdb.com/title/tt1979376/" },
  { seed:34, name:"Lady and the Tramp", year:1955, studio:"Disney", imdb:"https://www.imdb.com/title/tt0048280/" },
  { seed:35, name:"101 Dalmatians", year:1961, studio:"Disney", imdb:"https://www.imdb.com/title/tt0055254/" },
  { seed:36, name:"Peter Pan", year:1953, studio:"Disney", imdb:"https://www.imdb.com/title/tt0046183/" },
  { seed:37, name:"The Hunchback of Notre Dame", year:1996, studio:"Disney", imdb:"https://www.imdb.com/title/tt0116583/" },
  { seed:38, name:"Snow White", year:1937, studio:"Disney", imdb:"https://www.imdb.com/title/tt0029583/" },
  { seed:39, name:"Big Hero 6", year:2014, studio:"Disney", imdb:"https://www.imdb.com/title/tt2245084/" },
  { seed:40, name:"Raya and the Last Dragon", year:2021, studio:"Disney", imdb:"https://www.imdb.com/title/tt5109280/" },
  { seed:41, name:"Cars", year:2006, studio:"Pixar", imdb:"https://www.imdb.com/title/tt0317219/" },
  { seed:42, name:"Pinocchio", year:1940, studio:"Disney", imdb:"https://www.imdb.com/title/tt0032910/" },
  { seed:43, name:"Fantasia", year:1940, studio:"Disney", imdb:"https://www.imdb.com/title/tt0032455/" },
  { seed:44, name:"Luca", year:2021, studio:"Pixar", imdb:"https://www.imdb.com/title/tt12801262/" },
  { seed:45, name:"Pocahontas", year:1995, studio:"Disney", imdb:"https://www.imdb.com/title/tt0114148/" },
  { seed:46, name:"Alice in Wonderland", year:1951, studio:"Disney", imdb:"https://www.imdb.com/title/tt0043274/" },
  { seed:47, name:"Inside Out 2", year:2024, studio:"Pixar", imdb:"https://www.imdb.com/title/tt22022452/" },
  { seed:48, name:"The Princess and the Frog", year:2009, studio:"Disney", imdb:"https://www.imdb.com/title/tt0780521/" },
  { seed:49, name:"A Bug's Life", year:1998, studio:"Pixar", imdb:"https://www.imdb.com/title/tt0120623/" },
  { seed:50, name:"Dumbo", year:1941, studio:"Disney", imdb:"https://www.imdb.com/title/tt0033563/" },
  { seed:51, name:"Robin Hood", year:1973, studio:"Disney", imdb:"https://www.imdb.com/title/tt0070608/" },
  { seed:52, name:"Monsters University", year:2013, studio:"Pixar", imdb:"https://www.imdb.com/title/tt1453405/" },
  { seed:53, name:"Treasure Planet", year:2002, studio:"Disney", imdb:"https://www.imdb.com/title/tt0133240/" },
  { seed:54, name:"Atlantis: The Lost Empire", year:2001, studio:"Disney", imdb:"https://www.imdb.com/title/tt0230025/" },
  { seed:55, name:"The Great Mouse Detective", year:1986, studio:"Disney", imdb:"https://www.imdb.com/title/tt0091149/" },
  { seed:56, name:"The Rescuers Down Under", year:1990, studio:"Disney", imdb:"https://www.imdb.com/title/tt0100477/" },
  { seed:57, name:"The Sword in the Stone", year:1963, studio:"Disney", imdb:"https://www.imdb.com/title/tt0057546/" },
  { seed:58, name:"The Aristocats", year:1970, studio:"Disney", imdb:"https://www.imdb.com/title/tt0065421/" },
];

export const PLAYIN: Movie[] = [
  { seed:59, name:"Bolt", year:2008, studio:"Disney", imdb:"https://www.imdb.com/title/tt0397892/" },
  { seed:60, name:"Meet the Robinsons", year:2007, studio:"Disney", imdb:"https://www.imdb.com/title/tt0396555/" },
  { seed:61, name:"Brother Bear", year:2003, studio:"Disney", imdb:"https://www.imdb.com/title/tt0328880/" },
  { seed:62, name:"The Rescuers", year:1977, studio:"Disney", imdb:"https://www.imdb.com/title/tt0076618/" },
  { seed:63, name:"Oliver & Company", year:1988, studio:"Disney", imdb:"https://www.imdb.com/title/tt0095776/" },
  { seed:64, name:"Elemental", year:2023, studio:"Pixar", imdb:"https://www.imdb.com/title/tt15789038/" },
  { seed:65, name:"Turning Red", year:2022, studio:"Pixar", imdb:"https://www.imdb.com/title/tt8097030/" },
  { seed:66, name:"Onward", year:2020, studio:"Pixar", imdb:"https://www.imdb.com/title/tt7146812/" },
  { seed:67, name:"Chicken Little", year:2005, studio:"Disney", imdb:"https://www.imdb.com/title/tt0371606/" },
  { seed:68, name:"Incredibles 2", year:2018, studio:"Pixar", imdb:"https://www.imdb.com/title/tt3606756/" },
  { seed:69, name:"Ralph Breaks the Internet", year:2018, studio:"Disney", imdb:"https://www.imdb.com/title/tt5848272/" },
  { seed:70, name:"The Good Dinosaur", year:2015, studio:"Pixar", imdb:"https://www.imdb.com/title/tt1979388/" },
];

// Play-in pairings: indices into PLAYIN
export const PIP: [number, number][] = [[4,2],[1,9],[0,7],[3,6],[5,8],[10,11]];

// Round of 64 pairings: indices into combined array (MAIN[0..57] + playin winners[58..63])
export const R1: [number, number][] = [
  [0,58],[31,32],[15,48],[16,41],[8,53],[23,40],[7,54],[25,38],
  [3,59],[29,36],[13,51],[18,47],[5,43],[26,33],[11,52],[20,46],
  [6,60],[27,39],[12,50],[19,49],[9,55],[22,45],[4,61],[21,44],
  [1,62],[30,35],[14,37],[17,42],[2,63],[24,34],[10,56],[28,57],
];

export const RND: string[] = ["Round of 64","Round of 32","Sweet 16","Elite 8","Final Four","Championship"];
export const REG: string[] = ["Legends & Legacies","Heart & Heartbreak","Magic & Mischief","Worlds Apart"];

export const STATIC_META: StaticMeta = {
  1:  { runtime:"88 min",  rating:"8.5", plot:"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.", poster:"https://image.tmdb.org/t/p/w185/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg" },
  2:  { runtime:"81 min",  rating:"8.3", plot:"A cowboy doll is profoundly jealous when a new spaceman action figure supplants him as the top toy in a boy's bedroom. When circumstances separate them from their owner, the duo have to put aside their differences to return to him.", poster:"https://image.tmdb.org/t/p/w185/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg" },
  3:  { runtime:"100 min", rating:"8.2", plot:"After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.", poster:"https://image.tmdb.org/t/p/w185/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg" },
  4:  { runtime:"84 min",  rating:"8.0", plot:"A prince cursed to spend his days as a hideous monster sets out to regain his humanity by earning a young woman's love.", poster:"https://image.tmdb.org/t/p/w185/hUJ0UvQ5tgE2Z9WpfuduVSdiCiU.jpg" },
  5:  { runtime:"83 min",  rating:"7.6", plot:"A mermaid princess makes a Faustian bargain in an attempt to become human and win a prince's love.", poster:"https://image.tmdb.org/t/p/w185/plcZXvI310FkbwIptvd6rqk63LP.jpg" },
  6:  { runtime:"96 min",  rating:"8.3", plot:"78-year-old Carl Fredricksen travels to South America in his house equipped with balloons, inadvertently taking a young stowaway.", poster:"https://image.tmdb.org/t/p/w185/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg" },
  7:  { runtime:"90 min",  rating:"8.0", plot:"A kind-hearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.", poster:"https://image.tmdb.org/t/p/w185/eLFfl7vS8dkeG1hKp5mwbm37V83.jpg" },
  8:  { runtime:"95 min",  rating:"8.1", plot:"After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions, Joy, Fear, Anger, Disgust, and Sadness, conflict on how best to navigate a new city, house, and school.", poster:"https://image.tmdb.org/t/p/w185/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg" },
  9:  { runtime:"105 min", rating:"8.4", plot:"Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.", poster:"https://image.tmdb.org/t/p/w185/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg" },
  10: { runtime:"102 min", rating:"7.4", plot:"Fearless optimist Anna teams up with rugged mountain man Kristoff and his loyal reindeer Sven in an epic journey to find Anna's sister Elsa, whose icy powers have trapped the kingdom of Arendelle in eternal winter.", poster:"https://image.tmdb.org/t/p/w185/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg" },
  11: { runtime:"115 min", rating:"8.0", plot:"While trying to lead a quiet suburban life, a family of undercover superheroes are forced into action to save the world.", poster:"https://image.tmdb.org/t/p/w185/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg" },
  12: { runtime:"98 min",  rating:"8.4", plot:"A robot who is responsible for cleaning a waste-covered Earth meets another robot and falls in love with her. Together, they set out on a journey that will alter the fate of mankind.", poster:"https://image.tmdb.org/t/p/w185/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg" },
  13: { runtime:"87 min",  rating:"7.7", plot:"To save her father from death in the army, a young maiden secretly goes in his place and becomes one of China's greatest heroines in the process.", poster:"https://image.tmdb.org/t/p/w185/jAbexAtB0aSfP5Ay4TpWHARyVnG.jpg" },
  14: { runtime:"100 min", rating:"7.7", plot:"The magically long-haired Rapunzel has spent her entire life in a tower, but now that a runaway thief has stumbled upon her, she is about to discover the world for the first time, and who she really is.", poster:"https://image.tmdb.org/t/p/w185/ym7Kst6a4uodryxqbGOxmewF235.jpg" },
  15: { runtime:"92 min",  rating:"8.1", plot:"In order to power the city, monsters have to scare children so that they scream. However, the children are toxic to the monsters, and after a child gets through, two monsters realize things may not be what they think.", poster:"https://image.tmdb.org/t/p/w185/wFSpyMsp7H0ttERbxY7Trlv8xry.jpg" },
  16: { runtime:"107 min", rating:"7.6", plot:"In ancient Polynesia, when a terrible curse incurred by the demigod Maui reaches Moana's island, she answers the Ocean's call to seek out Maui to set things right.", poster:"https://image.tmdb.org/t/p/w185/9tzN8sPbyod2dsa0lwuvrwBDWra.jpg" },
  17: { runtime:"111 min", rating:"8.1", plot:"A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.", poster:"https://image.tmdb.org/t/p/w185/t3vaWRPSf6WjDSamIkKDs1iQWna.jpg" },
  18: { runtime:"103 min", rating:"8.3", plot:"The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it's up to Woody to convince the other toys that they weren't abandoned and to return home.", poster:"https://image.tmdb.org/t/p/w185/AbbXspMOwdvwWZgVN0nabZq03Ec.jpg" },
  19: { runtime:"85 min",  rating:"7.4", plot:"A young and parentless girl adopts a 'dog' from the local pound, completely unaware that it's supposedly a dangerous scientific experiment that's taken refuge on Earth and is now hiding from its creator and those who see it as a m...", poster:"https://image.tmdb.org/t/p/w185/d73UqZWyw3MUMpeaFcENgLZ2kWS.jpg" },
  20: { runtime:"78 min",  rating:"7.4", plot:"Emperor Kuzco is turned into a llama by his ex-administrator Yzma, and must now regain his throne and his human form with the help of Pacha, a gentle llama herder.", poster:"https://image.tmdb.org/t/p/w185/isA0acj3ONKBLp1pKadUNzxEPFv.jpg" },
  21: { runtime:"74 min",  rating:"7.3", plot:"When Cinderella's cruel stepmother prevents her from attending the Royal Ball, she gets some unexpected help from the lovable mice Gus and Jaq and from her Fairy Godmother.", poster:"https://image.tmdb.org/t/p/w185/4nssBcQUBadCTBjrAkX46mVEKts.jpg" },
  22: { runtime:"93 min",  rating:"7.3", plot:"The son of Zeus and Hera is stripped of his immortality as an infant and must become a true hero in order to reclaim it.", poster:"https://image.tmdb.org/t/p/w185/dK9rNoC97tgX3xXg5zdxFisdfcp.jpg" },
  23: { runtime:"75 min",  rating:"7.2", plot:"After being snubbed by the royal family, a malevolent fairy places a curse on a princess which only a prince can break, along with the help of three good fairies.", poster:"https://image.tmdb.org/t/p/w185/n3pxoMDDxp10c1smgbDzW4bwlzq.jpg" },
  24: { runtime:"102 min",  rating:"7.2", plot:"An extraordinary family, the Madrigals, live hidden in the mountains of Colombia, in a magical house called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift - every child except one, Mi...", poster:"https://image.tmdb.org/t/p/w185/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg" },
  25: { runtime:"100 min", rating:"8.0", plot:"Joe is a middle-school band teacher whose life hasn't quite gone the way he expected. His true passion is jazz. But when he travels to another realm to help someone find their passion, he soon discovers what it means to have soul.", poster:"https://image.tmdb.org/t/p/w185/6jmppcaubzLF8wkXM36ganVISCo.jpg" },
  26: { runtime:"108 min", rating:"8.0", plot:"In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy.", poster:"https://image.tmdb.org/t/p/w185/hlK0e0wAQ3VLuJcsfIYPvb4JVud.jpg" },
  27: { runtime:"69 min",  rating:"7.3", plot:"The story of a young deer growing up in the forest.", poster:"https://image.tmdb.org/t/p/w185/wV9e2y4myJ4KMFsyFfWYcUOawyK.jpg" },
  28: { runtime:"101 min", rating:"7.7", plot:"Ralph is tired of playing the role of a bad guy and embarks on a journey to become a video game hero. But he accidentally lets loose a deadly enemy that threatens the entire arcade.", poster:"https://image.tmdb.org/t/p/w185/zWoIgZ7mgmPkaZjG0102BSKFIqQ.jpg" },
  29: { runtime:"88 min",  rating:"7.3", plot:"A man raised by gorillas must decide where he really belongs when he discovers he is a human.", poster:"https://image.tmdb.org/t/p/w185/bTvHlcqiOjGa3lFtbrTLTM3zasY.jpg" },
  30: { runtime:"78 min",  rating:"7.6", plot:"Bagheera the Panther and Baloo the Bear have a difficult time trying to convince a boy to leave the jungle for human civilization.", poster:"https://image.tmdb.org/t/p/w185/yN1kuupnPTLUprgfvC5WapgrxG4.jpg" },
  31: { runtime:"93 min",  rating:"7.1", plot:"Determined to make her own path in life, Princess Merida defies a custom that brings chaos to her kingdom. Granted one wish, Merida must rely on her bravery and her archery skills to undo a beastly curse.", poster:"https://image.tmdb.org/t/p/w185/1XAuDtMWpL0sYSFK0R6EZate2Ux.jpg" },
  32: { runtime:"92 min",  rating:"7.9", plot:"When Woody is stolen by a toy collector, Buzz and his friends set out on a rescue mission to save Woody before he becomes a museum toy property with his roundup gang Jessie, Prospector, and Bullseye.", poster:"https://image.tmdb.org/t/p/w185/yFWQkz2ynjwsazT6xQiIXEUsyuh.jpg" },
  33: { runtime:"100 min", rating:"7.6", plot:"When Woody, Buzz, and the gang join Bonnie on a road trip with her new craft project turned toy, Forky, the innocent little spork's antics launch Woody on a wild quest.", poster:"https://image.tmdb.org/t/p/w185/w9kR8qbmQ01HwnvK4alvnQ2ca0L.jpg" },
  34: { runtime:"76 min",  rating:"7.3", plot:"The romantic tale of a sheltered uptown Cocker Spaniel dog and a streetwise downtown Mutt.", poster:"https://image.tmdb.org/t/p/w185/340NcWz9SQXWQyf4oicMxjbrLOb.jpg" },
  35: { runtime:"79 min",  rating:"7.3", plot:"When a litter of Dalmatian puppies are abducted by the minions of Cruella De Vil, the owners must find them before she uses them for a diabolical fashion statement.", poster:"https://image.tmdb.org/t/p/w185/kSlYq6FrBUviGSEh8v4L9nrSnBT.jpg" },
  36: { runtime:"77 min",  rating:"7.3", plot:"Wendy and her brothers are whisked away to the magical world of Neverland with the hero of their stories, Peter Pan.", poster:"https://image.tmdb.org/t/p/w185/fJJOs1iyrhKfZceANxoPxPwNGF1.jpg" },
  37: { runtime:"91 min",  rating:"7.0", plot:"A deformed bell-ringer must assert his independence from a vicious government minister in order to help his friend, a gypsy dancer.", poster:"https://image.tmdb.org/t/p/w185/hImMgT9B27evYSRmfztqdDtX6qi.jpg" },
  38: { runtime:"83 min",  rating:"7.6", plot:"Exiled into the dangerous forest by her wicked stepmother, a princess is rescued by seven dwarf miners who make her part of their household.", poster:"https://image.tmdb.org/t/p/w185/3VAHfuNb6Z7UiW12iYKANSPBl8m.jpg" },
  39: { runtime:"102 min", rating:"7.8", plot:"A special bond develops between plus-sized inflatable robot Baymax and prodigy Hiro Hamada, who together team up with a group of friends to form a band of high-tech heroes.", poster:"https://image.tmdb.org/t/p/w185/2mxS4wUimwlLmI1xp6QW6NSU361.jpg" },
  40: { runtime:"107 min", rating:"7.3", plot:"In a realm known as Kumandra, a re-imagined Earth inhabited by an ancient civilization, a warrior named Raya is determined to find the last dragon.", poster:"https://image.tmdb.org/t/p/w185/5nVhgCzxKbK47OLIKxCR1syulOn.jpg" },
  41: { runtime:"116 min", rating:"7.3", plot:"On the way to the biggest race of his life, a hotshot rookie race car gets stranded in a rundown town and learns that winning isn't everything in life.", poster:"https://image.tmdb.org/t/p/w185/2Touk3m5gzsqr1VsvxypdyHY5ci.jpg" },
  42: { runtime:"88 min",  rating:"7.5", plot:"A living puppet, with the help of a cricket as his conscience, must prove himself worthy to become a real boy.", poster:"https://image.tmdb.org/t/p/w185/bnZJrLRnoQHpzEJdka1KYfsAF3N.jpg" },
  43: { runtime:"124 min", rating:"7.7", plot:"A series of eight famous pieces of classical music, conducted by Leopold Stokowski and interpreted in animation by Walt Disney's team of artists.", poster:"https://image.tmdb.org/t/p/w185/5m9njnidjR0syG2gpVPVgcEMB2X.jpg" },
  44: { runtime:"95 min",  rating:"7.4", plot:"On the Italian Riviera, an unlikely but strong friendship grows between a human being and a sea monster disguised as a human.", poster:"https://image.tmdb.org/t/p/w185/9x4i9uKGXt8IiiIF5Ey0DIoY738.jpg" },
  45: { runtime:"81 min",  rating:"6.7", plot:"An English soldier and the daughter of an Algonquin chief share a romance when English colonists invade seventeenth century Virginia.", poster:"https://image.tmdb.org/t/p/w185/kZ1ft0QZ4e3zDUPMBftEkwI9ftd.jpg" },
  46: { runtime:"75 min",  rating:"7.3", plot:"Alice stumbles into the world of Wonderland. Will she get home? Not if the Queen of Hearts has her way.", poster:"https://image.tmdb.org/t/p/w185/20cvfwfaFqNbe9Fc3VEHJuPRxmn.jpg" },
  47: { runtime:"96 min", rating:"7.5", plot:"A sequel that features Riley entering puberty and experiencing brand new, more complex emotions as a result.", poster:"https://image.tmdb.org/t/p/w185/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg" },
  48: { runtime:"97 min",  rating:"7.2", plot:"A waitress desperate to fulfill her dreams as a restaurant owner is set on a journey to turn a frog prince back into a human, but she has to face the same problem after she kisses him.", poster:"https://image.tmdb.org/t/p/w185/v6nAUs62OJ4DXmnnmPFeVmMz8H9.jpg" },
  49: { runtime:"95 min",  rating:"7.2", plot:"A misfit ant, looking for \"warriors\" to save his colony from greedy grasshoppers, recruits a group of bugs that turn out to be an inept circus troupe.", poster:"https://image.tmdb.org/t/p/w185/Ah3J9OJVc2CNCuH2zMydXy9fmIC.jpg" },
  50: { runtime:"64 min",  rating:"7.2", plot:"Ridiculed because of his enormous ears, a young circus elephant is assisted by a mouse to achieve his full potential.", poster:"https://image.tmdb.org/t/p/w185/4x9FmvdJ464Fg7A9XcbYSmxfVw3.jpg" },
  51: { runtime:"83 min",  rating:"7.5", plot:"The story of the legendary British outlaw portrayed with the characters as anthropomorphic animals.", poster:"https://image.tmdb.org/t/p/w185/x9AvkYek0bGdxQSZ8W3lAjGrREm.jpg" },
  52: { runtime:"104 min", rating:"7.2", plot:"A look at the relationship between Mike Wazowski and James P. \"Sully\" Sullivan during their days at Monsters University, when they weren't necessarily the best of friends.", poster:"https://image.tmdb.org/t/p/w185/y7thwJ7z5Bplv6vwl6RI0yteaDD.jpg" },
  53: { runtime:"95 min",  rating:"7.2", plot:"Jim Hawkins is a teenager who finds the map of a great treasure hidden by a space pirate. Together with some friends, he sets off in a large spaceship, shaped like a caravel, on his quest.", poster:"https://image.tmdb.org/t/p/w185/kNhZkR3UNbXfvESQo7mJpOi4tGd.jpg" },
  54: { runtime:"83 min",  rating:"6.4", plot:"A clueless boss has no idea what to do with his mundane office worker whose refusal of duties only gets worse each passing minute.", poster:"https://image.tmdb.org/t/p/w185/swYfLGplXAle5CenmWVYpRSomCp.jpg" },
  55: { runtime:"74 min",  rating:"7.1", plot:"Basil, the rodent Sherlock Holmes, investigates the kidnapping of a toy maker and uncovers its link to his archenemy, Professor Ratigan.", poster:"https://image.tmdb.org/t/p/w185/9uDr7vfjCFr39KGCcqrk44Cg7fQ.jpg" },
  56: { runtime:"77 min",  rating:"6.8", plot:"R.A.S. agents Miss Bianca and Bernard race to Australia to save a little boy and a rare golden eagle from a murderous poacher.", poster:"https://image.tmdb.org/t/p/w185/5koTDBmMAkJOgAe4PL4163UKjvG.jpg" },
  57: { runtime:"79 min",  rating:"7.1", plot:"A poor boy named Arthur learns the power of love, kindness, knowledge and bravery with the help of a wizard called Merlin in the path to become one of the most beloved kings in English history.", poster:"https://image.tmdb.org/t/p/w185/7lyeeuhGAJSNXYEW34S8mJ1bwI8.jpg" },
  58: { runtime:"78 min",  rating:"7.1", plot:"With the help of a smooth talking tomcat, a family of Parisian felines set to inherit a fortune from their owner try to make it back home after a jealous butler kidnaps them and leaves them in the country.", poster:"https://image.tmdb.org/t/p/w185/1BVOSmQUhphMgnTxnXyfQ9tL1Sc.jpg" },
  59: { runtime:"96 min",  rating:"6.8", plot:"The canine star of a fictional sci-fi/action show that believes his powers are real embarks on a cross country trek to save his co-star from a threat he believes is just as real.", poster:"https://image.tmdb.org/t/p/w185/v5aC4nrzXFGJDWY4JO1eengXzqk.jpg" },
  60: { runtime:"95 min",  rating:"6.8", plot:"Lewis is a brilliant inventor who meets mysterious stranger named Wilbur Robinson, whisking Lewis away in a time machine and together they team up to track down Bowler Hat Guy in a showdown that ends with an unexpected twist of fate.", poster:"https://image.tmdb.org/t/p/w185/naya0zF4kT401Sx15AtwB9vpcJr.jpg" },
  61: { runtime:"85 min",  rating:"6.9", plot:"When a young Inuit hunter needlessly kills a bear, he is magically changed into a bear himself as punishment with a talkative cub being his only guide to changing back.", poster:"https://image.tmdb.org/t/p/w185/otptPbEY0vBostmo95xwiiumMJm.jpg" },
  62: { runtime:"77 min",  rating:"6.9", plot:"Two mice of the Rescue Aid Society search for a little girl kidnapped by unscrupulous treasure hunters.", poster:"https://image.tmdb.org/t/p/w185/9jpDjrRyvv9Nw0piXOpHHQTfxw9.jpg" },
  63: { runtime:"74 min",  rating:"6.6", plot:"A lost and alone kitten joins a gang of dogs engaged in petty larceny in New York City.", poster:"https://image.tmdb.org/t/p/w185/x8XqdiZ0Oxu5iXF9SiFub9Lae8J.jpg" },
  64: { runtime:"101 min", rating:"7.0", plot:"Follow Ember and Wade, in a city where fire, water, earth and air live together.", poster:"https://image.tmdb.org/t/p/w185/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg" },
  65: { runtime:"100 min", rating:"6.9", plot:"A thirteen-year-old girl named Mei Lee is torn between staying her mother's dutiful daughter and the changes of adolescence.", poster:"https://image.tmdb.org/t/p/w185/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg" },
  66: { runtime:"102 min", rating:"7.4", plot:"Teenage elf brothers Ian and Barley embark on a magical quest to spend one more day with their late father.", poster:"https://image.tmdb.org/t/p/w185/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg" },
  67: { runtime:"81 min",  rating:"5.7", plot:"After ruining his reputation with the town, a courageous chicken must come to the rescue of his fellow citizens when aliens start an invasion.", poster:"https://image.tmdb.org/t/p/w185/87FpA4b90eTaw3U6zmCNikoPLir.jpg" },
  68: { runtime:"118 min", rating:"7.5", plot:"The Incredibles family takes on a new mission which involves a change in family roles: Bob Parr (Mr. Incredible) must manage the house while his wife Helen (Elastigirl) goes out to save the world.", poster:"https://image.tmdb.org/t/p/w185/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg" },
  69: { runtime:"112 min", rating:"7.0", plot:"On a quest to save the video game 'Sugar Rush' and to find a replacement, Ralph and his best friend Vanellope travel to the World Wide Web through a Wi-Fi router they find at the arcade.", poster:"https://image.tmdb.org/t/p/w185/iVCrhBcpDaHGvv7CLYbK6PuXZo1.jpg" },
  70: { runtime:"93 min",  rating:"6.7", plot:"In a world where dinosaurs and humans live side-by-side, an Apatosaurus named Arlo makes an unlikely human friend.", poster:"https://image.tmdb.org/t/p/w185/8RSkxOO80btfKjyiC5ZiTaCHIT8.jpg" },
};

export const ALL_MOVIES: Movie[] = [...MAIN, ...PLAYIN];

// Movies ordered by when they first appear in the bracket (play-in → R1 region order)
export const BRACKET_ORDER: Movie[] = [
  ...PIP.flatMap(([a,b]) => [PLAYIN[a], PLAYIN[b]]),
  ...R1.flatMap(([a,b]) => { const out: Movie[]=[]; if(a<58) out.push(MAIN[a]); if(b<58) out.push(MAIN[b]); return out; }),
];

export const CLR: Record<string, ColorScheme> = {
  Disney: { bg:"#0d0d1e", ac:"#9d8fe0", gl:"rgba(157,143,224,.25)", tx:"#b8b0e8" },
  Pixar:  { bg:"#0d0d1e", ac:"#9d8fe0", gl:"rgba(157,143,224,.25)", tx:"#b8b0e8" },
};
